
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body class="<?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>" itemscope itemtype="http://schema.org/WebPage">
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>      
       <?php echo $this->getChildHtml('header') ?> 

      <div class="home-slider-container">
        <div class="main-col main-col--visible">
          <div class="home-slider">
            <a class="home-slider-nav home-slider-prev jsHomeSliderPrev" href="#"><span class="i icon-arrow-left"></span></a>
            <a class="home-slider-nav home-slider-next jsHomeSliderNext" href="#"><span class="i icon-arrow-right"></span></a>

            <div class="bxslider">
              <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_home_slider_banner_block')->toHtml() ?>
            </div>
          </div>
        </div>
      </div>
   
      <div class="our-features-box mob">
         <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_header_block')->toHtml() ?>  
      </div>
      
      <div class="main-col">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_home_offer_banner_block')->toHtml() ?>
      </div>

      <div class="recommend-pro">
        <div><?php echo $this->getLayout()->createBlock('catalog/product_list')->setTemplate('catalog/product/recommended.phtml')->toHtml(); ?></div>
      </div>
                        
       <div class="main-col">  
          <article>             
              <?php echo $this->getChildHtml('breadcrumbs') ?>               
              <?php echo $this->getChildHtml('global_messages') ?>
              <?php echo $this->getChildHtml('content') ?>
          </article>
      </div> <!--main-col-->

      <div class="main-col">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_twitter_slider')->toHtml() ?>
      </div>
      
      <!-- Home Lastest Blog Block -->
      <?php // echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_home_latest_blog_block')->toHtml() ?>

      <?php echo $this->getChildHtml('footer') ?>
      <?php echo $this->getChildHtml('before_body_end') ?>
      <?php echo $this->getAbsoluteFooter() ?>     

      <?php if(Mage::app()->getStore()->getConfig('lambysettings/lambysettings_newsletterpopup/newsletterpopup_enable')==1){?>
          <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe_home_popup.phtml')->toHtml() ; ?>
      <?php } ?>
  
</body>
</html>

