
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>

<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="page-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h2><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h2>
</div> <!--page-title-->

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php /* if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; */ ?>

<div class="categories-slider">
    <div class="bxslider">

        <div class="categories-slide" style="background-image: url('<?php echo $this->helper('core/js')->getJsSkinUrl('easylink/img/categories-slider/categories_slider_01.jpg') ?>');">
            <div class="categories-slide-content">
                <h2 class="categories-slide-title">Summer sale</h2>
                <h3 class="categories-slide-subtitle">Dementia care products</h3>
                <p>Search fot product designed to assist people with memory issues.</p>
            </div>
        </div>

        <div class="categories-slide" style="background-image: url('<?php echo $this->helper('core/js')->getJsSkinUrl('easylink/img/categories-slider/categories_slider_01.jpg') ?>');">
            <div class="categories-slide-content">
                <h2 class="categories-slide-title">Summer sale</h2>
                <h3 class="categories-slide-subtitle">Dementia care products</h3>
                <p>Search fot product designed to assist people with memory issues.</p>
            </div>
        </div>

        <div class="categories-slide" style="background-image: url('<?php echo $this->helper('core/js')->getJsSkinUrl('easylink/img/categories-slider/categories_slider_01.jpg') ?>');">
            <div class="categories-slide-content">
                <h2 class="categories-slide-title">Summer sale</h2>
                <h3 class="categories-slide-subtitle">Dementia care products</h3>
                <p>Search fot product designed to assist people with memory issues.</p>
            </div>
        </div>

        <div class="categories-slide" style="background-image: url('<?php echo $this->helper('core/js')->getJsSkinUrl('easylink/img/categories-slider/categories_slider_01.jpg') ?>');">
            <div class="categories-slide-content">
                <h2 class="categories-slide-title">Summer sale</h2>
                <h3 class="categories-slide-subtitle">Dementia care products</h3>
                <p>Search fot product designed to assist people with memory issues.</p>
            </div>
        </div>

        <div class="categories-slide" style="background-image: url('<?php echo $this->helper('core/js')->getJsSkinUrl('easylink/img/categories-slider/categories_slider_01.jpg') ?>');">
            <div class="categories-slide-content">
                <h2 class="categories-slide-title">Summer sale</h2>
                <h3 class="categories-slide-subtitle">Dementia care products</h3>
                <p>Search fot product designed to assist people with memory issues.</p>
            </div>
        </div>

    </div>
</div>

<?php /* if($_description=$this->getCurrentCategory()->getDescription()): ?>
<div class="category-description std">
<?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
</div>
<?php endif; */ ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
