<?php $footer_type = Mage::getStoreConfig('lambysettings/lambysettings_appearance/footer'); ?>

<?php /*
<!-- Logo Brand Block -->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_logo_brand_block')->toHtml() ?>
*/ ?>

<footer>



<div class="footer <?php echo $footer_type;?>">

<!-- BEGIN INFORMATIVE FOOTER -->  
  <?php switch ($footer_type) {
      case 'informative' :
          ?>

<div class="newsletter-wrap">
  <div class="inner">
     <?php if (Mage::getStoreConfig('lambysettings/lambysettings_social/social_link')) { ?>
    <div class="social">      
       <ul class="link">
          <li class="social-txt"><h4>follow us</h4></li>
        <?php if (Mage::getStoreConfig('lambysettings/lambysettings_social/facebook_social_link')) { ?>
          <li class="fb"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('lambysettings/lambysettings_social/facebook_social_link_path') ?>" title="<?php echo $this->__('Facebook');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('lambysettings/lambysettings_social/twitter_social_link')) {
        ?>
          <li class="tw"><a target="_blank" rel="nofollow"  href="<?php echo Mage::getStoreConfig('lambysettings/lambysettings_social/twitter_social_link_path') ?>" title="<?php echo $this->__('Twitter');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('lambysettings/lambysettings_social/googleplus_social_link')) {
        ?>
          <li class="googleplus"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('lambysettings/lambysettings_social/googleplus_social_link_path') ?>" title="<?php echo $this->__('GooglePlus');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('lambysettings/lambysettings_social/rss_social_link')) {
        ?>
          <li class="rss"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('lambysettings/lambysettings_social/rss_social_link_path') ?>" title="<?php echo $this->__('RSS');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('lambysettings/lambysettings_social/pinterest_social_link')) {
        ?>
          <li class="pintrest"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('lambysettings/lambysettings_social/pinterest_social_link_path') ?>" title="<?php echo $this->__('PInterest');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('lambysettings/lambysettings_social/linkedin_social_link')) {
        ?>
          <li class="linkedin"><a  target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('lambysettings/lambysettings_social/linkedin_social_link_path') ?>" title="<?php echo $this->__('Linkedin');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('lambysettings/lambysettings_social/youtube_social_link')) {
        ?>
          <li class="youtube"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('lambysettings/lambysettings_social/youtube_social_link_path') ?>" title="<?php echo $this->__('Youtube');?>"></a></li>
        <?php } ?>
       </ul>
    </div> <!--social-->
    <?php } ?>
    <!-- Footer Newsletter -->
    <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe_footer.phtml')->toHtml() ; ?>
  </div> <!--inner-->
</div> <!--newsletter-wrap-->

<div class="inner">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_footer_about_us')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_footer_information_links_block')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_footer_contact_us')->toHtml() ?>
</div> <!--inner-->

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_footer_links')->toHtml() ?>

<!-- BEGIN SIMPLE FOOTER -->  
          <?php
          break;
      case 'simple' :
      default: ?>
     
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('lamby_footer_links')->toHtml() ?>

     <?php     
  }
  ?> 

</div> <!--footer-->

</footer>

<?php if (Mage::getStoreConfig('lambysettings/lambysettings_footer/footer_google_analytics')): ?>
<?php echo Mage::getStoreConfig('lambysettings/lambysettings_footer/footer_google_analytics_path') ?>       
<?php endif; ?>

<script type="text/javascript">
  jQuery(function($) {

    jQuery('.home-offer-header').matchHeight();
    jQuery('.products-grid .item .item-inner .item-info .info-inner').matchHeight();
    jQuery('.category-subcategory').matchHeight();
    jQuery('.products-grid .item .item-inner .item-info .info-inner .item-title').matchHeight();

    // jQuery('.products-grid .item .item-inner .item-info .info-inner .item-title').dotdotdot();

  });
</script>
