
<?php if (Mage::getStoreConfig('lambysettings/lambysettings_products/upsell_product')): ?>

<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="upsell-slider">
  <div class="new_title center">
    <h2><span><?php echo $this->__('Customers Also Bought') ?></span></h2>
  </div> <!--new_title center-->
<a href="#" class="jcarousel-prev-horizontal2" id="products_slider_prev"></a>
<a href="#" class="jcarousel-next-horizontal2" id="products_slider_next"></a>
<div class="jcarousel-skin-tango4">
  <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;">
    <div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;">
   <ul id="featured_products_slider" class="products-grid jcarousel-list jcarousel-list-horizontal" style="overflow: hidden; position: relative; top: 0px; margin: 0px; padding: 0px; left: 0px; width: 2460px;">

    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>

 <li class="item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
<div class="item-inner">
    <div class="product-wrapper">
      <div class="thumb-wrapper">
         <?php echo $this->helper('lambysettings')->getLabel($_link);  ?>
        <?php if(Mage::app()->getStore()->getConfig('lambysettings/lambysettings_quickview/enable')==1){?>
         <a class="thumb" data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('lambysettings/index/view/id/'.$_link->getId());?>');"><span class="face"><img alt="<?php echo $this->htmlEscape($_link->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(170,206) ?>"></span><span class="face back"><img alt="<?php echo $this->htmlEscape($_link->getName()) ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'thumbnail')->resize(170,206) ?>">          
              <span class="quick-view"><span><i>&nbsp;</i><?php echo $this->__('Quick View') ?></span></span>                                                    
          </span></a>
          <?php } else {  ?> 
             <a class="thumb" href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>">
              <span class="face">
                <img alt="<?php echo $this->htmlEscape($_link->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(170,206) ?>">
              </span>
              <?php /*<span class="face back">
                <img alt="<?php echo $this->htmlEscape($_link->getName()) ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'thumbnail')->resize(170,206) ?>">
              </span>*/ ?>
            </a>
          <?php } ?>
      </div> <!--thumb-wrapper-->
      <?php /*<div class="actions">
        <span class="add-to-links">
           <a href="<?php echo $this->helper('wishlist')->getAddUrl($_link) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist');?>"><span><?php echo $this->__('Add to Wishlist');?></span></a>
            <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare');?>"><span><?php echo $this->__('Add to Compare');?></span></a>
        </span> <!--add-to-links-->
      </div> <!--actions-->*/ ?>
    </div> <!--product-wrapper-->
    <div class="item-info">
      <div class="info-inner">
         <div class="item-title">
             <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>">
                  <?php $prod_name = $this->htmlEscape($_link->getName()) ; 
                  if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
             </a>
          </div> <!--item-title-->
          <div class="item-description">More info about product</div>
          <div class="item-content">
            <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_link->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
            <div class="item-price"><?php echo $this->getPriceHtml($_link, true) ?></div>
          </div> <!--item-content-->
      </div> <!--info-inner-->
      <div class="actions">         
            <?php if($_link->isSaleable()): ?>
              <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
            <?php else: ?>
              <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>          
        </div> <!--actions-->
    </div> <!--item-info-->                        
   </div> <!--item-inner-->     
            </li> 
            <?php endif; ?>

        <?php endfor; ?> 
    <?php endfor; ?>

  </ul>
   </div> <!--jcarousel-clip jcarousel-clip-horizontal-->
 </div> <!--jcarousel-container jcarousel-container-horizontal-->
</div> <!--jcarousel-skin-tango4-->

<script type="text/javascript">decorateTable('upsell-product-table')</script>

<script type="text/javascript">
jQuery(document).ready(function($) {

        function mycarousel_initCallback(carousel) {

            $('#products_slider_next').bind('click', function() {
                carousel.next();
                return false;
            });
            $('#products_slider_prev').bind('click', function() {
                carousel.prev();
                return false;
            });
        };

    $('#featured_products_slider').jcarousel({
            scroll: 1,
        initCallback: mycarousel_initCallback,
            buttonNextHTML: null,
            buttonPrevHTML: null
    });
});
</script>   
<div id="mgkquickview">
<div id="magikloading" style="display:none;text-align:center;margin-top:400px;"><img src="<?php echo $this->getSkinUrl('images/mgkloading.gif');?>" alt="loading">
</div></div>
<script type="text/javascript">
function callQuickView(qurl) { 
    jQuery('#mgkquickview').show();
    jQuery('#magikloading').show();
    jQuery.get(qurl, function(data) {
      jQuery.fancybox(data);
      jQuery('#magikloading').hide();
jQuery('#mgkquickview').hide();
    });
 }
 
</script>

</div> <!--upsell-slider-->

<?php endif ?>

<?php endif; ?> 
