<?php 
/* Top shopping Cart  */ 
?>





<div class="header-big-buttons">

  <a href="<?php echo $this->getUrl('')?>customer/account/" class="header-big-button">
    <span class="i icon-profile"></span>
    <span class="header-big-button-label">Account</span>
  </a>

  <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="header-big-button jsBasketButton">
    <span class="i icon-basket"></span>
    <span class="header-big-button-label">My Basket</span>

    <?php // if (Mage::helper('checkout/cart')->getSummaryCount() > 1): ?>
    <div class="header-big-button-count">1<?php echo Mage::helper('checkout/cart')->getSummaryCount(); ?></div>
    <?php // endif; ?>
  </a>

  <?php /*
  <div class="top-cart-contain">
    <div class="mini-cart">
      <div class="top-cart-content arrow_box jsTopCartContent">
        <?php $_items = $this->getRecentItems() ?>
        <?php if(count($_items)): ?>   
        <div class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></div>

        <ul id="cart-sidebar" class="mini-products-list">
          <?php foreach($_items as $_item): ?>
          <?php echo $this->getItemHtml($_item) ?>
          <?php endforeach; ?>
        </ul>  

        <div class="top-subtotal">
          <?php echo $this->__('Subtotal:');?>
          <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
        </div> <!--top-subtotal-->

        <div class="actions">
          <button type="button" class="view-cart" onclick="window.location='<?php echo $this->getUrl('checkout/cart') ?>';" title="<?php echo $this->__('View Cart') ?>" ><span><?php echo $this->__('View Cart') ?></span></button>                 
          <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><?php echo $this->__('Checkout') ?></span></button>                         
        </div>  <!--actions-->

        <?php else: ?>               
        <p class="a-center noitem"><?php echo $this->__('You have no items in your shopping cart.') ?></p>               
        <?php endif ?>
      </div> <!--top-cart-content-->
    </div> <!--mini-cart-->
  </div> <!--top-cart-contain-->
  */ ?>

</div>











