<?php 
/* Top shopping Cart  */ 
?>

<div class="header-big-buttons">

  <a href="<?php echo $this->getUrl('')?>customer/account/" class="header-big-button">
    <span class="i icon-profile"></span>
    <span class="header-big-button-label">Account</span>
  </a>

  <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="header-big-button jsBasketButton">
    <span class="i icon-basket"></span>
    <span class="header-big-button-label">My Basket</span>

    <?php if (Mage::helper('checkout/cart')->getSummaryCount() > 1): ?>
    <div class="header-big-button-count"><?php echo Mage::helper('checkout/cart')->getSummaryCount(); ?></div>
    <?php endif; ?>
  </a>

</div>











